/**
 * @file screens.h
 * @brief Rallybox Screen Definitions & Object Hierarchy
 * @author EEZ Studio Generator + Rallybox Team
 * @developer Akhil
 *
 * Defines all screens and their associated LVGL objects in a central structure.
 * This file is generated by EEZ Studio but included here for reference and documentation.
 *
 * Screen Structure:
 * - BootingScreen: Professional 10-second splash screen with spinner animation
 * - Dashboard: Main monitoring interface with WiFi, SD card, and system stats
 *
 * Object Access:
 * All LVGL objects are accessible via the global 'objects' variable:
 * @code
 * extern objects_t objects;
 *
 * // Update a label
 * lv_label_set_text(objects.dashboard_uptime_1, "01:23:45");
 *
 * // Check object validity
 * if (objects.wifi_connection != NULL) {
 *     // Safe to use
 * }
 * @endcode
 *
 * Object Naming Convention:
 * - {screen}_{component}_{instance}
 * - Examples:
 *   - booting_title → Boot screen, title text
 *   - dashboard_uptime_1 → Dashboard, uptime display
 *   - sdcard_storage_1_1 → SD card section, slot 1, storage bar
 *   - wifi_connection → WiFi section, connection status
 *
 * Component Types:
 * - Label (lv_label_t): Text display
 * - Image (lv_img_t): Icons/pictures
 * - Button (lv_btn_t): Clickable controls
 * - Checkbox (lv_checkbox_t): Toggle indicators
 * - Progress Bar (lv_bar_t): Visual indicators (storage usage)
 * - Spinner (lv_spinner_t): Animated loading indicator
 * - Container (lv_obj_t): Layout groups
 *
 * @note Do not modify this file manually (auto-generated by EEZ Studio)
 * @see ui.h for public functions
 * @see ui_logic.c for update functions that modify these objects
 */

#ifndef EEZ_LVGL_UI_SCREENS_H
#define EEZ_LVGL_UI_SCREENS_H

#include "lvgl.h"

#ifdef __cplusplus
extern "C" {
#endif

    /* SCREEN ENUMERATION
     *
     * All screens in the UI are defined here as enum values. Use these to
     * identify screens when calling loadScreen().
     */

     /// Screen ID enumeration (used by loadScreen())
    enum ScreensEnum
    {
        _SCREEN_ID_FIRST = 1,

        /// Booting screen (splash, shows during first 10 seconds)
        SCREEN_ID_BOOTINGSCREEN = 1,

        /// Dashboard screen (main monitoring interface)
        SCREEN_ID_DASHBOARD = 2,

        _SCREEN_ID_LAST = 2
    };

    /* GLOBAL OBJECT STRUCTURE
     *
     * Contains pointers to all LVGL objects created by EEZ Studio.
     * Access any object via: objects.{object_name}
     */

     /// Global container for all LVGL object pointers
    typedef struct _objects_t
    {
        // ─── Screen Root Objects ───────────────────────────────────────────
        /// Root object for booting screen (1280×720 container)
        lv_obj_t* bootingscreen;

        /// Root object for dashboard screen (1280×720 container)
        lv_obj_t* dashboard;

        // ─── Booting Screen Objects ────────────────────────────────────────
        /// "Rally Box" title text (Montserrat 30pt, white)
        lv_obj_t* booting_title;

        /// Status label below title (Montserrat 16pt, white)
        lv_obj_t* booting_label;

        /// Animated rotating spinner indicator
        lv_obj_t* booting_spinner;

        // ─── Menu/Navigation ───────────────────────────────────────────────
        /// Container for menu buttons or tabs
        lv_obj_t* obj0;
        lv_obj_t* obj1;
        lv_obj_t* menu;

        // ─── Dashboard Header ───────────────────────────────────────────────
        /// Section subtitle (e.g., "Dashboard")
        lv_obj_t* subtitle_dashbaord_1;

        /// Main dashboard title
        lv_obj_t* dashboard_title_1;

        /// Container for system status section
        lv_obj_t* obj2;
        lv_obj_t* obj3;

        // ─── SD Card 1 Section (Internal SDMMC) ─────────────────────────────
        /// SD card icon for slot 2 (display position)
        lv_obj_t* sd_card_icon_2_2;

        /// SD1 title label
        lv_obj_t* sd_card_title_2_1;

        /// SD1 read/write counter display ("R:42 W:15")
        lv_obj_t* read_write_label_2_1;

        /// SD1 checkbox indicator (mount status)
        lv_obj_t* active_checkbox_sd_card_2_1;

        /// SD1 status label ("OK" or "FAIL")
        lv_obj_t* sdcard_label_2_1;

        /// SD1 checkbox (alternative display)
        lv_obj_t* active_checkbox_sd_card_1_1;

        /// SD1 read/write label
        lv_obj_t* read_write_label_1_1;

        /// SD1 status label
        lv_obj_t* sdcard_label_1_1;

        /// SD1 storage usage progress bar (visual capacity indicator)
        lv_obj_t* sdcard_storage_1_1;

        /// SD card icon for external slot
        lv_obj_t* sd_card_icon_2_3;

        // ─── Dashboard Metrics ─────────────────────────────────────────────
        /// Uptime display ("HH:MM:SS" format, updated 1 Hz)
        lv_obj_t* dashboard_uptime_1;

        /// Top bar title ("System Status")
        lv_obj_t* system_status_top_bar_title_1;

        /// WiFi connection status display
        lv_obj_t* wifi_connection;

        /// CPU load and heap memory display ("CPU: X% | Heap: Y KB")
        lv_obj_t* system_load_status_1;

        /// WiFi icon on dashboard
        lv_obj_t* dashbaord_wifi_icon_1;

        /// System load section title
        lv_obj_t* system_load_title_1;

        /// Number/counter title
        lv_obj_t* title_4;

        /// Error status title
        lv_obj_t* error_title_1;

        /// Error count or status display
        lv_obj_t* error_status_1;

        // ─── SD Card Control Buttons ───────────────────────────────────────
        /// Format SD Card 2 button
        lv_obj_t* format_sd_card2;

        /// Format SD2 text/label
        lv_obj_t* format_sdcard_2_text_label;

        /// Format SD Card 1 button
        lv_obj_t* format_sd_card1;

        /// Format SD1 text/label
        lv_obj_t* format_sdcard_1_text_label_1;

        /// Test SD Card 1 mount button
        lv_obj_t* test_sd_card1_mount_2;

        /// Test SD2 text/label
        lv_obj_t* test_sdcard_2_text_label;

        /// Test SD Card 1 button
        lv_obj_t* test_sd_card1_mount;

        /// Test SD1 text/label
        lv_obj_t* test_sdcard_1_text_label;

        // ─── WiFi Settings Page ─────────────────────────────────────────────
        /// WiFi settings page/screen container
        lv_obj_t* wifi_page;

        /// WiFi page internal container
        lv_obj_t* obj4;

        /// WiFi Connect button
        lv_obj_t* wifi_conenct_button_1;

        /// Input box container
        lv_obj_t* input_box_1;

        /// WiFi password input text area
        lv_obj_t* wifi_password_1;

        /// WiFi SSID input text area
        lv_obj_t* wifi_ssid_1;

        /// SSID label
        lv_obj_t* ssid_1;

        /// WiFi page subtitle
        lv_obj_t* wifi_subtitle_1;

        /// On-screen keyboard widget
        lv_obj_t* ui_keyboard_1;

        /// WiFi screen title
        lv_obj_t* titile_wifi_screen_1;

        /// Brand name display
        lv_obj_t* brand_name_wifi_screen_1;

        /// WiFi icon on WiFi screen
        lv_obj_t* wifi_icon_wifi_screen_1;

        // ─── Bluetooth Page ───────────────────────────────────────────────
        /// Bluetooth page container tab
        lv_obj_t* bluetooth_page;

        /// Bluetooth page title label
        lv_obj_t* bluetooth_title;

        /// Bluetooth live status label
        lv_obj_t* bluetooth_status_label;

        /// Dropdown listing visible BLE devices
        lv_obj_t* bluetooth_device_dropdown;

        /// Manual refresh button for BLE list
        lv_obj_t* bluetooth_refresh_button;

        /// Connect button for selected BLE device
        lv_obj_t* bluetooth_connect_button;

        // ─── GNSS Page ───────────────────────────────────────────────────
        /// GNSS page container tab
        lv_obj_t* gnss_page;

        /// GNSS page title label
        lv_obj_t* gnss_title;

        /// GNSS status label
        lv_obj_t* gnss_status_label;

        /// GNSS baud rate input
        lv_obj_t* gnss_baud_input;

        /// GNSS TX GPIO input
        lv_obj_t* gnss_tx_input;

        /// GNSS RX GPIO input
        lv_obj_t* gnss_rx_input;

        /// GNSS start/stop listener button
        lv_obj_t* gnss_start_stop_button;

        /// GNSS UART message dump panel
        lv_obj_t* gnss_dump_panel;
    } objects_t;

    /* Global object reference (access all objects via this) */
    extern objects_t objects;

    /* SCREEN CREATION & UPDATE FUNCTIONS
     *
     * Called during ui_init() to create all screen objects.
     * Also includes per-screen tick functions for animations/updates.
     */

     /**
      * @brief Create booting screen and all child objects
      * Creates the splash screen with title, label, and spinner
      */
    void create_screen_bootingscreen(void);

    /**
     * @brief Update booting screen animations (called each frame)
     * Handles spinner rotation and any time-based effects
     */
    void tick_screen_bootingscreen(void);

    /**
     * @brief Create dashboard screen and all monitoring widgets
     * Creates all dashboard objects (metrics, buttons, displays)
     */
    void create_screen_dashboard(void);

    /**
     * @brief Update dashboard animations (called each frame)
     * Handles any dashboard-specific animations or updates
     */
    void tick_screen_dashboard(void);

    /**
     * @brief Call tick function for a specific screen
     * @param screenId Screen ID to tick (from enum ScreensEnum)
     */
    void tick_screen_by_id(enum ScreensEnum screenId);

    /**
     * @brief Call tick function for screen by index
     * @param screen_index Screen index (0-based)
     */
    void tick_screen(int screen_index);

    /**
     * @brief Create all screens (called by ui_init)
     * Initializes BootingScreen and Dashboard
     */
    void create_screens(void);

#ifdef __cplusplus
}
#endif

#endif /*EEZ_LVGL_UI_SCREENS_H*/